### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by ds2k5** [TheChosenNopler/OpenCore-Optiplex-7010#1]
Hi,
thanks for your work
tryed your EFI

Select in boot menu the USB-Key with the EFI for boot...
got only a black screen...

any hint how to get error messages or find why nothing more happen ?

**Comment by TheChosenNopler** [comment]
Please create your own EFI using the OpenCore guide. This EFI is going on 2 years old and I am not maintaining it. Even if I was it is for **my** specific hardware configuration, and you should not be using any premade EFI
